services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./service1:/var/tempData
    networks:
      - network_app_service1
      - network_multi
    depends_on:
      - postgreDB_service1

  postgreDB_service1:
    image: postgres:14-alpine
    container_name: postgreDB_service1
    restart: unless-stopped
    environment:
      - DB_HOST=postgreDB_service1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - '5433:5432'
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - network_app_service1
networks:
  network_app_service1:
    driver: bridge