services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./service1:/var/tempData
    networks:
      - network_app_service1
      - network_multi
    depends_on:
      - postgreDB_service1

  postgreDB_service1:
    image: postgres:14-alpine
    container_name: postgreDB_service1
    restart: unless-stopped
    environment:
      - DB_HOST={DB_HOST}
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_DB}
    ports:
      - '{DB_SERVICE1_EXTERNAL_PORT}:{DB_SERVICE1_INTERNAL_PORT}'
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - network_app_service1
networks:
  network_app_service1:
    driver: bridge